# Generated by Django 4.0.6 on 2023-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_memory', models.PositiveIntegerField(default=69)),
                ('total_memory', models.PositiveIntegerField(default=69)),
                ('used_swap', models.PositiveIntegerField(default=69)),
                ('total_swap', models.PositiveIntegerField(default=69)),
            ],
        ),
    ]
