# Generated by Django 4.0.6 on 2023-04-09 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('mac_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff account is activated')),
                ('is_active', models.BooleanField(default=True, verbose_name='account is activated')),
                ('is_admin', models.BooleanField(default=False, verbose_name='staff account')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SysInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel_version', models.CharField(max_length=25)),
                ('host_name', models.CharField(max_length=50)),
                ('name', models.CharField(default='ubuntu', max_length=20)),
                ('os_version', models.CharField(max_length=25)),
                ('cpu_count', models.PositiveIntegerField(blank=True)),
                ('cpus', models.JSONField(blank=True, default=None, null=True)),
                ('temp', models.JSONField(blank=True, default=None, null=True)),
                ('sys_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_memory', models.PositiveIntegerField(default=69)),
                ('total_memory', models.PositiveIntegerField(default=69)),
                ('used_swap', models.PositiveIntegerField(default=69)),
                ('total_swap', models.PositiveIntegerField(default=69)),
                ('sys_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.sysinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=69)),
                ('name', models.CharField(max_length=69)),
                ('written_bytes', models.PositiveIntegerField(default=0)),
                ('total_written_bytes', models.PositiveIntegerField(default=0)),
                ('read_bytes', models.PositiveIntegerField(default=0)),
                ('total_read_bytes', models.PositiveIntegerField(default=0)),
                ('sys_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.sysinfo')),
            ],
        ),
    ]
