# Generated by Django 4.0.6 on 2023-04-08 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel_version', models.CharField(max_length=25)),
                ('host_name', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=25)),
                ('cpu_count', models.PositiveIntegerField()),
                ('cpus', models.JSONField()),
                ('temp', models.JSONField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_memory', models.PositiveIntegerField(default=69)),
                ('total_memory', models.PositiveIntegerField(default=69)),
                ('used_swap', models.PositiveIntegerField(default=69)),
                ('total_swap', models.PositiveIntegerField(default=69)),
                ('sys_id', models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='api.sysinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=69)),
                ('disk_usage', models.CharField(max_length=69)),
                ('sys_id', models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='api.sysinfo')),
            ],
        ),
    ]
